## Numpy 
numeric python Arrays, arrays multidimensionais (matriz) Elementos tem que ter o mesmo Processamento rápido

In [69]:
# importar a biblioteca
import numpy as np

In [12]:
# Criar um array
array = np.array([1, 3, 5, 7])
print(array)

[1 3 5 7]


In [14]:
#Tipo: type()
print(type(array))

<class 'numpy.ndarray'>


In [16]:
# Definir o tipo dos elementos
# Array de floats
array_float = np.array([1.2, 3.6, 4.99999])
print(array_float)

[1.2     3.6     4.99999]


In [50]:
array_float = np.array([1, 2, 30], dtype = np.float64)
print(array_float)

[ 1.  2. 30.]


In [48]:
# Array de inteiros
array_int = np.array([1, 2, 30], dtype = np.int32)
print(array_int)

[ 1  2 30]


## Alterar o tipo do array

In [46]:
# Alterar de float para inteiro
array1 = np.array([1.2, 4.8, 8.3, 9.999])

array1_convertido = array1.astype(np.int32)
print(array1_convertido)


[1 4 8 9]


In [44]:
# Alterar de inteiro para float
array2 = np.array([1, 6, 8, 3])

array2_int = array2.astype(np.float64)
print(array2_int)

[1. 6. 8. 3.]


## Arrays Multidimencionais

In [40]:
# Criar um array bidimensional (matriz)
# linhas X colunas 
matriz = np.array([[1, 2, 3], [3, 4, 5]])
print(matriz)

[[1 2 3]
 [3 4 5]]


In [42]:
# Para verificar o formato (tamanho) da matriz 
print(matriz.shape)

(2, 3)


In [36]:
# Criar uma matriz contendo elementos de valor zero
matriz_zero = np.zeros([4, 2])
print(matriz_zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [34]:
#Criar uma matriz contendo 1
matriz_um = np.ones([3, 4])
print(matriz_um)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
# Criar uma matriz 2 X 3 de 0 inteiros 
matriz_zero_int = np.zeros([2, 3], dtype = np.int32)
print(matriz_zero_int)

[[0 0 0]
 [0 0 0]]


In [30]:
#Matriz identidade
# Matriz quadrada (mesmo número de linhas e colunas)
# Diagonal principal tem valor 1
matriz_identidade = np.eye(3)
print(matriz_identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Valores Aleatórios

In [80]:
#Array com valores aleatórios entr 0 e 1
array_aleatorio = np.random.random(4)
print(array_aleatorio)

[0.43741369 0.90566557 0.28019953 0.88210546]


In [82]:
# Matriz com valores aleatórios entre 0 e 1
matriz_aleatoria = np.random.random([2, 3])
print(matriz_aleatoria)

[[0.83774223 0.8809405  0.46234549]
 [0.13000531 0.63510922 0.63774149]]


In [84]:
# Array de valores aleatorios inteiros
array_ale_int = np.random.randint(4, size = 5) #0, 1, 2, 3
print(array_ale_int)


[1 0 1 2 3]


In [86]:
# Matriz de valores aleatorios inteiros
matriz_ale_int = np.random.randint(11, size = (3, 4))
print(matriz_ale_int)

[[7 8 6 9]
 [5 0 3 1]
 [9 4 0 3]]
